assignment/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings 

app_name = 'assignment'
 
urlpatterns=[
    path('dummyhome',views.dummyhome,name='dummyhome'),
    path('AssignmentFaculty',views.AssignmentFaculty,name='AssignmentFaculty'),
    path('Assignmentview',views.Assignmentview,name='Assignmentview'),
    path('dummyhome_student',views.dummyhome_student,name='dummyhome_student'),
    path('AssignmentStudent',views.AssignmentStudent,name='AssignmentStudent'),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)


notes_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('',include('signup.urls')),
    path('admin/', admin.site.urls),
    path('assignment/',include('assignment.urls')),
    path('notesd/', include('notesd.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)



notesd/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns=[
    path('search',views.search,name='search'),
    path('SearchPage',views.SearchPage,name='SearchPage'),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

signup/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings 
from assignment.views import dummyhome,dummyhome_student


urlpatterns=[
    path('',views.home,name='home'),
    path('signup',views.signup,name='signup'),
    path('facultysignup',views.facultysignup,name='facultysignup'),
    path('login',views.login,name='login'),
    path('facultylogin',views.facultylogin,name='facultylogin'),
    path('thankyou1',views.thankyou1,name='thankyou1'),
    path('thankyou',views.thankyou,name='thankyou'),
    path('thankyou_student',views.thankyou_student,name='thankyou_student'),
    path('dummyhome_student',dummyhome_student,name='dummyhome_student'),
    path('dummyhome',dummyhome,name='dummyhome'),
    path('uploadpage', views.uploadpage,name='uploadpage'),
    path('uploadnotes/',views.uploadnotes,name='uploadnotes'),
    path('uploadasg/',views.uploadasg,name='uploadasg'),
    
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)


assignment/models.py
from django.db import models

# Create your models here.
class assignment_details(models.Model):
    registration = models.CharField(max_length=100,default=False)
    class_code = models.CharField(max_length=100)
    year= models.CharField(max_length=100)
    instructions= models.CharField(max_length=100)
    upload= models.FileField(upload_to='files',default='no file')
    # this is useful in admin
    

    def __str__(self):
        return f'{self.class_code} {self.year}'
    

class assignment_answer(models.Model):
    student_registration = models.CharField(max_length=100)
    class_code = models.CharField(max_length=100)
    upload_answer=models.FileField(upload_to='files/',default='no file')

    def __str__(self):
        return f'{self.student_registration}'



signup/models.py
from django.db import models

# Create your models here.

class signup_table(models.Model):
    firstname= models.CharField(max_length=100)
    lastname= models.CharField(max_length=100)
    yearofjoining= models.IntegerField()
    registration= models.CharField(max_length=100,default=123)
    pwd=models.CharField(max_length=100,default=123)
   
    # this is useful in admin
    def __str__(self):
        return f'{self.firstname} {self.lastname}'



class faculty_signup(models.Model):
    firstname= models.CharField(max_length=100)
    lastname= models.CharField(max_length=100)
    coursecode= models.CharField(max_length=20)
    registration= models.CharField(max_length=100,default=123)
    classnumber=models.CharField(max_length=20)
    pwd=models.CharField(max_length=100,default=123)
   
    # this is useful in admin
    def __str__(self):
        return f'{self.firstname} {self.lastname}'

class notes(models.Model):
    facultyname = models.CharField(max_length=100,default='aaaaaa')
    coursecode = models.CharField(max_length=100,default='00000')
    coursename = models.CharField(max_length=100,default='00000')
    topicname = models.CharField(max_length=100,default='aaaaaa')
    pdf = models.FileField(upload_to='notes/pdf/')
    
    def __str__(self):
        return self.topicname

class asg(models.Model):
    facultyname = models.CharField(max_length=100,default='aaaaaa')
    coursecode = models.CharField(max_length=100,default='00000')
    coursename = models.CharField(max_length=100,default='00000')
    topicname = models.CharField(max_length=100,default='aaaaaa')
    pdf = models.FileField(upload_to='notes/pdf/')
    
    def __str__(self):
        return self.topicname

         

assignment/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import assignment_details,assignment_answer

from signup import views
import mysql.connector
from operator import itemgetter


# Create your views here.
def AssignmentFaculty(request):
    if request.method=='POST':
        data=request.POST.get
        registration=data('registration',False)
        class_code=data('class_code',False)
        year=data('year',False)
        instructions=data('instructions',False)
        upload=request.FILES['upload']
        ins=assignment_details(class_code=class_code,year=year,instructions=instructions,upload=upload)
        ins.save()
        print("data has been saved")
        print(upload.name)
        print(upload.size)
        return redirect('thankyou')

    if request.method == 'GET':
        return render(request,'AssignmentFaculty.html')


def AssignmentStudent(request):
    query_results = assignment_details.objects.all()
    if request.method=='POST': 
        
            student_registration = request.POST.get('student_registration',False)
            class_code = request.POST.get('class_code',False)
            try:
                upload_answer=request.FILES['upload_answer']
                
            except:
                return render(request,'AssignmentStudent.html')
            ins=assignment_answer(student_registration=student_registration,upload_answer=upload_answer,class_code=class_code)
            ins.save()
            print("data has been saved")
            print(upload_answer.name)
            print(upload_answer.size)
            return redirect('thankyou_student')
        

    
    if request.method == 'GET':
        return render(request,'AssignmentStudent.html',{'assignments':query_results})


def dummyhome(request):
    return render(request, 'dummyhome.html')

def Assignmentview(request):
    
    query_results = assignment_answer.objects.all()
    return render(request, 'Assignmentview.html',{'assignments_answers':query_results})


def dummyhome_student(request):
    return render(request, 'dummyhome_student.html')

signup/views.py
from os import name
from django.db.models import fields
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import signup_table
from .models import faculty_signup
import mysql.connector
from operator import itemgetter
from notesd import *
from assignment import views
from .models import notes
from django.core.files.storage import FileSystemStorage
from django.views.generic.edit import CreateView


# Create your views here.
def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method=="POST":
        data=request.POST.get
        firstname=data('firstname',False)
        lastname=data('lastname',False)
        yearofjoining=data('yearofjoining',False)
        registration=data('registration',False)
        pwd=data('pwd',False)
        #rpwd=data('rpwd',False)
        #if pwd==rpwd:
        ins=signup_table(firstname=firstname,lastname=lastname,yearofjoining=yearofjoining,registration=registration,pwd=pwd)
        ins.save()
        print("data has been saved")
        return redirect('notesd/SearchPage')
 
    else:     
        return render(request,'signup.html')

def facultysignup(request):
    if request.method=="POST":
        data=request.POST.get
        firstname=data('firstname',False)
        lastname=data('lastname',False)
        coursecode=data('coursecode',False)
        registration=data('registration',False)
        classnumber=data('classnumber',False)
        pwd=data('pwd',False)
        #rpwd=data('rpwd',False)
        #if pwd==rpwd:
        ins=faculty_signup(firstname=firstname,lastname=lastname,coursecode=coursecode,registration=registration,classnumber=classnumber,pwd=pwd)
        ins.save()
        print("data has been saved")
        return redirect('uploadpage')
 
    else:     
        return render(request,'facultysignup.html')


def login(request):
    con1=mysql.connector.connect(host="localhost",user="root",passwd="mysql123",database="notes")
    cursor1=con1.cursor()
    con2=mysql.connector.connect(host="localhost",user="root",passwd="mysql123",database="notes")
    cursor2=con2.cursor()
    sql_reg="select registration from signup_signup_table"
    sql_pwd="select pwd from signup_signup_table"
    cursor1.execute(sql_reg)
    cursor2.execute(sql_pwd)
    r=[]
    p=[]
    for i in cursor1:
        r.append(i)
    for j in cursor2:
        p.append(j)
        
    res1=list(map(itemgetter(0),r))
    res2=list(map(itemgetter(0),p))

    if request.method=="POST":
        data=request.POST.get
        registration=data('registration',False)
        pwd=data('pwd',False)
        i=0
        k=len(res1)
        while i<k:
            if res1[i]==registration and res2[i]==pwd:
                return redirect('notesd/SearchPage')
            i = i+1
        return HttpResponse('<h1 style="font-size:30px">Wrong Registration no: or password</h1>')    
    else:     
        return render(request,'login.html')

def facultylogin(request):
    con1=mysql.connector.connect(host="localhost",user="root",password="mysql123",database="notes")
    cursor1=con1.cursor()
    con2=mysql.connector.connect(host="localhost",user="root",password="mysql123",database="notes")
    cursor2=con2.cursor()
    sql_reg="select registration from signup_faculty_signup"
    sql_pwd="select pwd from signup_faculty_signup"
    cursor1.execute(sql_reg)
    cursor2.execute(sql_pwd)
    r=[]
    p=[]
    for i in cursor1:
        r.append(i)
    for j in cursor2:
        p.append(j)
        
    res1=list(map(itemgetter(0),r))
    res2=list(map(itemgetter(0),p))

    if request.method=="POST":
        data=request.POST.get
        registration=data('registration',False)
        pwd=data('pwd',False)
        i=0
        k=len(res1)
        while i<k:
            if res1[i]==registration and res2[i]==pwd:
                return redirect('uploadpage')
            i=i+1
        return HttpResponse('<h1 style="font-size:30px">Wrong Registration no: or password</h1>')
    else:     
        return render(request,'facultylogin.html')

def thankyou(request):
    # here
    return render(request,'thankyou.html')

def thankyou1(request):
    # here
    return render(request,'thankyou1.html')

def thankyou_student(request):
    return render(request,'thankyou_student.html')

def uploadpage(request):
    return render(request, 'uploadpage.html')

def uploadnotes(request):
    if request.method=='POST':
        context={}
        data=request.POST.get
        facultyname=data('facultyname',False)
        coursecode=data('coursecode',False)
        coursename=data('coursename',False)
        topicname=data('topicname',False)
        pdf=request.FILES['pdf']
        ins=notes(facultyname=facultyname,coursecode=coursecode,coursename=coursename,topicname=topicname,pdf=pdf)
        ins.save()
        print("data has been saved")
        return redirect('thankyou1')
    else:    
        return render(request, 'uploadnotes.html')


def uploadasg(request):
    if request.method=='POST':
        context={}
        data=request.POST.get
        facultyname=data('facultyname',False)
        coursecode=data('coursecode',False)
        coursename=data('coursename',False)
        topicname=data('topicname',False)
        pdf=request.FILES['pdf']
        notes(facultyname=facultyname,coursecode=coursecode,coursename=coursename,topicname=topicname,pdf=pdf).save()
        print("data has been saved")
        return redirect('thankyou')
    else:    
        return render(request, 'uploadasg.html')



templates/AssignmentStudent.html
{% load static %}

{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
    body {
        background-color: rgb(44, 1, 75);
      }
      label  {
        color: white;
        padding: 20px 20px;
        font-size:17px ;
        margin: 5px 0;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
        display: inline-block; 
        width: 200px;
        text-align: left;
      }
      p {
        color: white;
      }
      input[type=file]{
        color: white;
        width: 25%;
        padding: 10px 20px;
        margin: 8px 0;
        outline: none;
      }
      input {
        width: 25%;
        padding: 10px 20px;
        margin: 8px 0;
        outline: none;
      }
      input:focus {
        background-color: lightblue;
      }
      input[type=submit]{
            background-color: darkcyan;
            border: none;
            color: black;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 15 px;
            cursor: pointer;
      }
      input[type=submit]:hover {
        background-color:rgb(191, 240, 95) ; 
        color: black;
      }
      
    
      
   
</style>
<body>
  <div class="logo">
    <a href="{% static 'AssignmentStudent.html' %}"><img src="{% static 'images/logon.png' %}" width="220px" height="57px" alt="#" /></a>
 </div>
    <h1 style="color:white;">SUBMIT ASSIGNMENT</h1>
    <form action="{% url 'assignment:AssignmentStudent' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
        <label for="student_registration">Registration number:</label>
        <input type="text" id="student_registration" name="student_registration"><br><br>
        {% for item in assignments %}
        <tr> 
            <p style="padding-left:20px">{{ item.class_code }} <br> <br> <br>
            {{ item.instructions }} <br>
            <br>
            <br>
            
            <a href="{{ item.upload.url }}" download >{{ item.upload }}</a></p>
            <label for="class_code">class code:</label>
            <input type="text" id="class_code" name="class_code"><br><br>
            <label for="upload_answer">Upload:</label>
            <input type="file" id="upload_answer" name="upload_answer"><br><br>

        </tr>
        {% endfor %}
        <input type="submit" value="Submit"><br>
    </table>

      </form>
</body>
</html>

templates/Assignmentview.html
{% load static %}

{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
    body {
        background-color: rgb(44, 1, 75);
      }
      label  {
        color: white;
        padding: 20px 20px;
        font-size:17px ;
        margin: 5px 0;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
        display: inline-block; 
        width: 200px;
        text-align: left;
      }
      p {
        color: white;
      }
      a {
        color: white; 
      }
      table, th, td {
        border: 1px solid white;
        padding: 2px;
      }
      tr 
      {
          color: white;
      }
      input[type=file]{
        color: white;
        width: 25%;
        padding: 10px 20px;
        margin: 8px 0;
        outline: none;
      }
      input {
        width: 25%;
        padding: 10px 20px;
        margin: 8px 0;
        outline: none;
      }
      input:focus {
        background-color: lightblue;
      }
      input[type=submit]{
            background-color: darkcyan;
            border: none;
            color: black;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 15 px;
            cursor: pointer;
      }
      input[type=submit]:hover {
        background-color:rgb(191, 240, 95) ; 
        color: black;
      }
      
    
      
   
</style>
<body>
  <div class="logo">
    <img src="{% static 'images/logon.png' %}" width="220px" height="57px" alt="#" /></a>
 </div>
    <h1 style="color:white;">View assignments</h1>

      {% csrf_token %}
      <table style="width:100%">
        <tr>
            <th>Registrations</th>
            <th>class code</th> 
            <th>File</th>
          </tr>
        {% for item in assignments_answers %}
        <tr> 
            <td>{{ item.student_registration }}</td>
            <td>{{ item.class_code }}</td>
            <td><a href="{{ item.upload_answer.url }}" download >{{ item.upload_answer }}</a></td>
        </tr>
        {% endfor %}
    </table>
    <p><a href="{% url 'uploadpage' %}">Back</a></p>


</body>
</html>

templates/SearchPage.html
{% load static %}
{% static "images" as baseUrl %}


<!DOCTYPE html>
<html>
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.hero-image {
  background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("/static/images/banner.jpg");
  height: 60%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

.hero-text {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: rgb(14, 1, 1);
}


</style>
</head>
<body>

<div class="hero-image">
  <div class="hero-text">
    <h1 style="font-size:70px">Notes on go</h1>
    
  </div>
</div>
</body>
  <head>
    <title>Notes</title>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>
  <body>
      <div class="container" style="color:rgb(5, 1, 14)">
        <br> <br>
       <h1>Notes</h1>
      </div>
  <div class="container">
      <h4></h4>
      <br>
    <form action="search" method="get" class="form-inline">
      {% csrf_token %}
      <label for="coursecode" style="font-size:20px">Course code:</label> &nbsp;
      <input name = "query1" type="text" class="notes_table" id="query1" placeholder="Enter Course code" style="font-size:20px"> &nbsp; &nbsp; &nbsp;
      <label for="coursename" style="font-size:20px">Course name:</label> &nbsp;
      <input name = "query2" type="text" class="notes_table" id="query2" placeholder="Enter Course name" style="font-size:20px"> &nbsp; &nbsp;
      <button type="submit" name="button" style="font-size:20px">Search</a></button>
    </form>
                
        
  </div>
<style>
.button {
  border: none;
  color: white;
  padding: 20px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  transition-duration: 0.4s;
  cursor: pointer;
  
}

.button1 {
  background-color: rgb(243, 192, 236);
  color: rgb(235, 220, 220);
  border: 2px solid #0c0242;
  position: absolute;
  top: 560px;
  right: 50px;
  
}

.button2 {
      
  border: 2px solid #0c0242;
  position: absolute;
  top: 20px;
  right: 15px;
  
}

.button3 {
      
  border: 2px solid #0c0242;
  position: absolute;
  top: 20px;
  right: 170px;
  
}

</style>


</head>
<body>

<button class="button button3" style="font-size:20px">
  <a href="{% url 'assignment:AssignmentStudent' %}">Submit Assignment</a></button>
<button class="button button2" style="font-size:20px">
    <a href="{% url 'home' %}">Logout</a></button>

</body>


</html>

templates/dummyhome.html
{% load static %}
{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
    body {
        background-color: rgb(44, 1, 75);
      }
      label  {
        color: white;
        padding: 20px 20px;
        font-size:20px ;
        margin: 5px 0;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
        display: inline-block; 
        width: 200px;
        text-align: left;
      }
      input {
        width: 25%;
        padding: 10px 20px;
        margin: 8px 0;
        border: 1px solid #555;
        outline: none;
      }
      input:focus {
        background-color: lightblue;
      }
      input[type=submit]{
            background-color: darkcyan;
            border: none;
            color: black;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            cursor: pointer;
      }
      input[type=submit]:hover {
        background-color:rgb(191, 240, 95) ; 
        color: black;
      }
      
    
      
   
</style>
<body>
  <div class="logo">
    <img src="{% static 'images/logon.png' %}" width="220px" height="57px" alt="#" />
 </div>
    <h1 style="color:white;">FACULTY HOME</h1>
      {% csrf_token %}
      <button ><a href="{% url 'assignment:AssignmentFaculty' %}">Create assignment</a></button>
      <button ><a href="{% url 'assignment:Assignmentview' %}">View assignments</a></button>
      <br><br><br>
      <button ><a href="{% url 'home' %}">Logout</a></button>
      </form>
</body>

templates/dummyhome_student.html
{% load static %}
{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
    body {
        background-color: rgb(44, 1, 75);
      }
      label  {
        color: white;
        padding: 20px 20px;
        font-size:20px ;
        margin: 5px 0;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
        display: inline-block; 
        width: 200px;
        text-align: left;
      }
      input {
        width: 25%;
        padding: 10px 20px;
        margin: 8px 0;
        border: 1px solid #555;
        outline: none;
      }
      input:focus {
        background-color: lightblue;
      }
      input[type=submit]{
            background-color: darkcyan;
            border: none;
            color: black;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            cursor: pointer;
      }
      input[type=submit]:hover {
        background-color:rgb(191, 240, 95) ; 
        color: black;
      }
      
    
      
   
</style>
<body>
  <div class="logo">
    <a href="{% static 'dummyhome.html' %}"><img src="{% static 'images/logon.png' %}" width="220px" height="57px" alt="#" /></a>
 </div>
    <h1 style="color:white;">STUDENT HOME</h1>
      {% csrf_token %}
      <button ><a href="{% url 'assignment:AssignmentStudent' %}">Submit assignment</a></button>

      </form>
</body>
</html>

templates/thankyou.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: rgb(44, 1, 75);">
    <h1 style="color:white;"> Assignment created </h1>
    <p style="color:white;"><a style="color: white;"  href="{% url 'uploadpage' %}"> Back to home page </a></p>
</body>
</html>

templates/uploadpage.html
{% load static %}
{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en">
   <head>
    <style>
        body {
          background-image: url('img.png');
          background-repeat: no-repeat;
          background-attachment: fixed; 
          background-size: auto;
        }
        </style>
        <style>
         .aligned {
            display: flex;
            align-items: center;
        }
           
        span {
            padding: 10px;
        }
            .button {
              border: none;
              color: white;
              padding: 32px 16px;;
              text-align: center;
              text-decoration: none;
              display: block;
              font-size: 12px;
              margin: 4px 2px;
              cursor: pointer;
            }
            .block-display button{
               margin-bottom:5px;
               display:block;
             }

            .button1 {background-color: #008CBA;
               padding: 12px 28px;
               border-radius: 12px;
               width: 100%;
               line-height: 1.2;
               display: block;
               }      
               
            </style>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Notes On Go</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
      <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif' %}" alt="#" /></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container">
               <div class="row">
                  <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="{% static 'home.html' %}"><img src="{% static 'images/logon.png' %}" alt="#" /></a>
                              <br><br>
                              <div>
                                 <button class="button button1" type="button" ><a href="uploadnotes" font-size: 14px;>Notes</a></button>
                                 <button class="button button1" type="button" ><a href="{% url 'assignment:AssignmentFaculty' %}" font-size: 14px;>Create assignment</a></button>
                                 <button class="button button1" type="button" ><a href="{% url 'assignment:Assignmentview' %}" font-size: 14px;>View Assignment</a></button>
            
                                 <button class="button button1" type="button" ><a href="{% url 'home' %}" font-size: 14px;>Logout</a></button>
                                 
                                 <br><br><br>
                                 

                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      <!-- banner -->
      <section class="banner_main">
         <div class="container">
            <div class="row d_flex">
               <div class="col-md-7">
                  <div class="text-img">
                    <figure><img src="{% static 'images/img.png' %}" /></figure>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <!-- end banner -->
      <!-- end contact -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <script src="{% static 'https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js' %}"></script>
   </body>
</html>
      